version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,kinesis
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - KINESIS_ERROR_PROBABILITY=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./.tmp:/tmp/localstack"
      - ./localstack:/docker-entrypoint-initaws.d
      - "/var/run/docker.sock:/var/run/docker.sock"
