
name: 'Telemetry Client CI'
on:
    pull_request:
    workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout branch
            uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version-file: '.nvmrc'
          - run: npm install
            working-directory: ./projects/user-telemetry-client
          - run: npm test
            working-directory: ./projects/user-telemetry-client

