
name: 'Telemetry Client CI'
on:
    push:
      paths:
       - 'projects/user-telemetry-client/**'
      branches:
       - main
       - beta
    pull_request:
      paths:
       - 'projects/user-telemetry-client/**'

jobs:
    ci:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: write
          id-token: write

        steps:
          - name: Checkout branch
            uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version-file: '.nvmrc'
          - run: npm install
            working-directory: ./projects/user-telemetry-client
          - run: npm test
            working-directory: ./projects/user-telemetry-client
          - run: npm run build
            working-directory: ./projects/user-telemetry-client
          - run: npm run release
            if: github.ref == 'refs/heads/main' ||  github.ref == 'refs/heads/beta'
            working-directory: ./projects/user-telemetry-client
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

