
name: 'Telemetry Client CI'
on:
    push:
      paths:
       - 'projects/user-telemetry-client/**'
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout branch
            uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version-file: '.nvmrc'
          - run: npm install
            working-directory: ./projects/user-telemetry-client
          - run: npm test
            working-directory: ./projects/user-telemetry-client
    semantic-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@db6e259b93f286e3416eef27aaae88935d16cf2e
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    release:
      runs-on: ubuntu-latest
      needs: [ci, semantic-lint]
      if: github.ref == 'refs/heads/main' ||  github.ref == 'refs/heads/beta'
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version-file: '.nvmrc'
        - run: npm install
          working-directory: ./projects/user-telemetry-client
        - run: npm run build
          working-directory: ./projects/user-telemetry-client
        - run: npm run release
          working-directory: ./projects/user-telemetry-client

